### ISSUE TITLE
Some questions about calibration parameters

### ISSUE THREAD

**Issue by Silverqwx** [vincentjzy/OpenCorr#15]
Hello,

I am trying to use the stereo-DIC module of OpenCorr.
It is successful when I process the provided data by demo code.
But When I tried to process my data, it failed to find the corresponding pixel coordinate in the other image.

So I am thinking maybe our coordinate systems are different.
I use OpenCV for calibration which provides the result with the Right Hand Coordinate System setting.
Could you tell me what is your coordinate system setting?

And another question is, when I use the code, I am not sure what is the exact meaning of rx, ry and rz.
For example, the rx, ry and rz of view1, are they the rotation vector parameters 
- from the world coordinate system to the view1 coordinate system? 
- or from the view1 coordinate system to the world coordinate system?
- or from the view1 coordinate system to the view2 coordinate system?
- or from the view2 coordinate system to the view1 coordinate system?

I will be so glad to receive help with these questions from you.

**Comment by vincentjzy** [comment]
The examples given in OpenCorr are from DIC challenge 2.0, in which the configuration is different from most of practices. In these examples, right camera, instead of left camera, is set as the principal camera. And the world coordinate system is fixed on the principal camera. If you use left camera as principal camera, the image collected by this camera should be assigned to view1. The translation vetcor (tx, ty, tz) and rotation vector (rx, ry, rz) are the relative parameters of view2 with respect to view1.

**Comment by Silverqwx** [comment]
Do you mean I should set it like this?

- view1:
  - left image from left camera
  - left intrinsic parameters
  - rotation (rx, ry, rz) and translation (tx, ty, tz) parameters which are 0
- view2:
  - right image from right camera
  - right intrinsic parameters
  - rotation (rx, ry, rz) and translation (tx, ty, tz) parameters which transfer coordinates from the Right Camera Coordinate System to the Left Coordinate System

**Comment by vincentjzy** [comment]
yes, try this way

**Comment by Silverqwx** [comment]
I am sorry.
It still does not work.
I have also tried different subset sizes and stop_conditions and search_steps.
Is there any other details I have overlooked do you think?

**Comment by vincentjzy** [comment]
You may share the images and calibration parameters in your cases, here or in QQ group. Let us see what we can do to help.

**Comment by Silverqwx** [comment]
Here is the images and calibration parameters.
Thank you so much for help!

[data.zip](https://github.com/vincentjzy/OpenCorr/files/13984554/data.zip)

**Comment by SCUTRLee** [comment]
@Silverqwx any contact information can you provide？Email, QQ or Wechat is ok

**Comment by SCUTRLee** [comment]
@Silverqwx  Any contact information can you provide？Email, QQ or Wechat is ok. I can look over your problem for you

**Comment by SCUTRLee** [comment]
@Silverqwx 我没能复现你说的问题，我使用sift特征点提供初值，icgn迭代优化可以成功的计算你提供的算例。如果你期望可以快速解决问题的话，可以加一下qq群(597895040)，我们详细可以交流一下你遇到的问题

**Comment by SCUTRLee** [comment]
@Silverqwx I can not reproduce the problem you mentioned, I use SIFT feature points to provide initial value, ICGN iterative optimization can successfully calculate the example you provide. If you are looking for a quick solution, you can add QQ Group (597895040) and we can talk about your problems in detail.
If you use the epipolar constraint module to search for the corresponding points in the right-hand view, I suspect that you have failed to provide a relatively accurate parallax estimate.

**Comment by Silverqwx** [comment]
@SCUTRLee Thank you so much for your help. This is my email: 13776000046@163.com. Could you send me your test code with my data?

**Comment by SCUTRLee** [comment]
Sure



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 6, 2024 12:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vincentjzy/OpenCorr] Some questions about calibration parameters(Issue #15)




 
@SCUTRLee Thank you so much for your help. This is my email: ***@***.*** Could you send me your test code with my data?

**Comment by Silverqwx** [comment]
@SCUTRLee
Thank you for your help with code.
However, It needs many points to process to get enough valid points with high score for initialization.
I am trying to process a few points, so I am trying to avoid using SIFT module, maybe using Epipolar-aided matching module only.

Could you help me have a check with my code?
I checked the parameters, it is the same as your demo.
My code is attached here.

[test_3d_reconstruction_epipolar.zip](https://github.com/vincentjzy/OpenCorr/files/14399800/test_3d_reconstruction_epipolar.zip)

**Comment by SCUTRLee** [comment]
你能否描述一下你遇到的问题？是运行遇到bug中断，还是结果出现了异常？这些异常具体表现为什么？




想吃鱼丸粿条
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vincentjzy/OpenCorr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月26日(星期一) 中午12:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vincentjzy/OpenCorr] Some questions about calibration parameters (Issue #15)





 
@SCUTRLee
 Thank you for your help with code.
 However, It needs many points to process to get enough valid points with high score for initialization.
 I am trying to process a few points, so I am trying to avoid using SIFT module, maybe using Epipolar-aided matching module only.
 
Could you help me have a check with my code?
 I checked the parameters, it is the same as your demo.
 My code is attached here.
 
test_3d_reconstruction_epipolar.zip

**Comment by Silverqwx** [comment]
OK.
It is ok with my code running.
No bug disruption.
However, the results have shown low scores, like 0.3, 0.2.

**Comment by SCUTRLee** [comment]
//create an instance of ICGN with the 2nd order shape function
&nbsp; &nbsp; int subset_radius_x = 9;
&nbsp; &nbsp; int subset_radius_y = 9;
&nbsp; &nbsp; float conv_criterion = 0.001f;
&nbsp; &nbsp; float stop_condition = 100;
&nbsp; &nbsp; ICGN2D2* icgn2 = new ICGN2D2(subset_radius_x, subset_radius_y, conv_criterion, stop_condition, cpu_thread_number);



你设置的子区半径太小了，子区内没有足够多的图像信息，导致匹配失败。在我给你例子中，子区半径设置为30


想吃鱼丸粿条
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vincentjzy/OpenCorr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月26日(星期一) 中午1:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vincentjzy/OpenCorr] Some questions about calibration parameters (Issue #15)





 
OK.
 It is ok with my code running.
 No bug disruption.
 However, the results have shown low scores, like 0.3, 0.2.

**Comment by Silverqwx** [comment]
I tried to change this value according to your suggestions.
However,  I tried 30, 50, 100, it works still not well.

**Comment by SCUTRLee** [comment]
你运行我发给你的代码能否得到正常的结果？

**Comment by Silverqwx** [comment]
Yes, your code can get good results.

**Comment by SCUTRLee** [comment]
那你可以尝试对比一下在你改动代码后哪个模块的输出结果出现了变化或者异常，由此来判断哪个地方的参数设置出现了问题。

**Comment by Silverqwx** [comment]
Actually, the code you sent to me and the code I sent to you are different.
Your code used SIFT module, which needs many points in processing to guarantee enough points with high scores for initialization.
I am trying to process a few points, so I am trying to avoid using SIFT module, maybe using Epipolar-aided matching module only.
And I met the problem here.

So maybe that's different.
